### ISSUE TITLE
[Log] Ex Nihilo: Sequentia spam in logs

### ISSUE THREAD

**Issue by EvanHsieh0415** [Mango-Minecraft-Project/Multi-Issue-Tracker#12]
```java
[Render thread/WARN] [no.ex.cl.re.CrucibleRender/]: [Ex Nihilo: Sequentia]: BlockState was null
```

**Comment by EvanHsieh0415** [comment]
- solution: use [Log Begone](https://www.curseforge.com/minecraft/mc-mods/log-begone) with this config:
  ```toml
  [logbegone]
  	regex = []
  	phrases = ["[Ex Nihilo: Sequentia]: BlockState was null"]
   ```
